insert into  IPTREATMENTPACKAGE( AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION_IN_WEEKS,TREATMENT_PACKAGE_NAME) Values ( 'Urology', 4000,  'Urine Test, Blood Test',4, 'Package 1');
insert into  IPTREATMENTPACKAGE( AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION_IN_WEEKS,TREATMENT_PACKAGE_NAME ) Values ( 'Orthopaedics', 2500,  'Bone-Scan, CT-Scan',4, 'Package 1');
insert into  IPTREATMENTPACKAGE(  AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION_IN_WEEKS,TREATMENT_PACKAGE_NAME) Values ( 'Urology', 5000,  'Cystoscopy, VCUG-XRAY',6, 'Package 2'); 
insert into  IPTREATMENTPACKAGE( AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION_IN_WEEKS,TREATMENT_PACKAGE_NAME ) Values ( 'Orthopaedics', 3000,  'MRI-Scan, DiscoGraphy',6, 'Package 2');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEAR, NAME) Values ( 'Orthopaedics', '9827369493',4,'Dr. Kunal Agarwal');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEAR, NAME) Values ( 'Urology', '8770279493',3,'Dr. Raman Take');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEAR, NAME) Values ( 'Orthopaedics', '9425638482',12,'Dr. Aniket Karanjkar');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEAR, NAME) Values ( 'Urology', '7999998182',15,'Dr. Ineaven Manickam');

